### ISSUE TITLE
`GLib-GIO-ERROR **: 21:44:01.959: Settings schema 'com.github.raibtoffoletto.adstruo.temps' is not installed`

### ISSUE THREAD

**Issue by LinArcX** [raibtoffoletto/adstruo#6]
Hi. I want to package your plugin for void-linux.
It compiles without any problem and intalled these files on my machine:
```
/usr/lib/switchboard/personal/libadstruo-plug.so
/usr/lib/wingpanel/libadstruo-keys.so
/usr/lib/wingpanel/libadstruo-temps.so
/usr/lib/wingpanel/libadstruo-weather.so
/usr/share/applications/com.github.raibtoffoletto.adstruo.desktop
/usr/share/icons/hicolor/scalable/apps/com.github.raibtoffoletto.adstruo.svg
/usr/share/icons/hicolor/scalable/status/com.github.raibtoffoletto.adstruo.temps.svg
/usr/share/icons/hicolor/scalable/status/temperature.svg
```

But wingpnale can't start and crash.(Even after i restarted the machine). This is the full error when try to start wingpanel:
```
(wingpanel:3339): GLib-GIO-ERROR **: 21:50:48.733: Settings schema 'com.github.raibtoffoletto.adstruo.temps' is not installed
[1]    3339 trace trap  wingpanel
```

**Comment by raibtoffoletto** [comment]
It seems that it failed to install the schema (done by the python script post install hook).
In my code I also should have checked for it to avoid wingpanel to crash... my bad.
I'm not familiar with Void, could you provide how are you installing pantheon on it? Are you compiling everything yourself or there is some meta package ported?
